import 'package:flutter/material.dart';

import '../model/sura.dart';

var kTxtStyleWhite = const TextStyle(
  color: Colors.white, fontSize: 15.5,
  // height: 0.5,
);

List<Map<int, int>> juzAndIndex = [
  {1: 1},
  {2: 22},
  {3: 42},
  {4: 62},
  {5: 82},
  {6: 102},
  {7: 121},
  {8: 142},
  {9: 162},
  {10: 182},
  {11: 201},
  {12: 222},
  {13: 242},
  {14: 262},
  {15: 282},
  {16: 302},
  {17: 322},
  {18: 342},
  {19: 362},
  {20: 382},
  {21: 402},
  {22: 422},
  {23: 442},
  {24: 462},
  {25: 482},
  {26: 502},
  {27: 522},
  {28: 542},
  {29: 562},
  {30: 582},
];

List<Sura> suraList = [
  Sura(
    name: 'الفاتحة',
    isMakka: true,
    verseNumbers: 7,
    pageNo: 1,
    order: 1,
  ),
  Sura(
    name: 'البقرة',
    isMakka: false,
    verseNumbers: 286,
    pageNo: 2,
    order: 2,
  ),
  Sura(
      name: 'آل عمران',
      isMakka: false,
      verseNumbers: 200,
      pageNo: 50,
      order: 3),
  Sura(
    name: 'النساء',
    isMakka: false,
    verseNumbers: 176,
    pageNo: 77,
    order: 4,
  ),
  Sura(
      name: 'المآئدة',
      isMakka: false,
      verseNumbers: 120,
      pageNo: 106,
      order: 5),
  Sura(
    name: 'الأنعام',
    isMakka: true,
    verseNumbers: 165,
    pageNo: 128,
    order: 6,
  ),
  Sura(
    name: 'الأعراف',
    isMakka: true,
    verseNumbers: 206,
    pageNo: 151,
    order: 7,
  ),
  Sura(
    name: 'الأنفال',
    isMakka: false,
    verseNumbers: 75,
    pageNo: 177,
    order: 8,
  ),
  Sura(
    name: 'التوبة',
    isMakka: false,
    verseNumbers: 129,
    pageNo: 187,
    order: 9,
  ),
  Sura(
    name: 'يُونس',
    isMakka: true,
    verseNumbers: 109,
    pageNo: 208,
    order: 10,
  ),
  Sura(
    name: 'هـود',
    isMakka: true,
    verseNumbers: 123,
    pageNo: 221,
    order: 11,
  ),
  Sura(
    name: 'يُوسف',
    isMakka: true,
    verseNumbers: 111,
    pageNo: 235,
    order: 12,
  ),
  Sura(
    name: 'الرعد',
    isMakka: false,
    verseNumbers: 43,
    pageNo: 249,
    order: 13,
  ),
  Sura(
    name: 'إبراهيم',
    isMakka: true,
    verseNumbers: 52,
    pageNo: 255,
    order: 14,
  ),
  Sura(
    name: 'الحجر',
    isMakka: true,
    verseNumbers: 99,
    pageNo: 262,
    order: 15,
  ),
  Sura(
    name: 'النحل',
    isMakka: true,
    verseNumbers: 128,
    pageNo: 267,
    order: 16,
  ),
  Sura(
    name: 'الإسراء',
    isMakka: true,
    verseNumbers: 111,
    pageNo: 282,
    order: 17,
  ),
  Sura(
    name: 'الكهف',
    isMakka: true,
    verseNumbers: 110,
    pageNo: 293,
    order: 18,
  ),
  Sura(
    name: 'مريم',
    isMakka: true,
    verseNumbers: 98,
    pageNo: 305,
    order: 19,
  ),
  Sura(
    name: 'طـه',
    isMakka: true,
    verseNumbers: 135,
    pageNo: 312,
    order: 20,
  ),
  Sura(
    name: 'الأنبياء',
    isMakka: true,
    verseNumbers: 112,
    pageNo: 322,
    order: 21,
  ),
  Sura(
    name: 'الحج',
    isMakka: false,
    verseNumbers: 78,
    pageNo: 332,
    order: 22,
  ),
  Sura(
    name: 'المؤمنون',
    isMakka: true,
    verseNumbers: 118,
    pageNo: 342,
    order: 23,
  ),
  Sura(
    name: 'النور',
    isMakka: false,
    verseNumbers: 64,
    pageNo: 350,
    order: 24,
  ),
  Sura(
    name: 'الفرقان',
    isMakka: true,
    verseNumbers: 77,
    pageNo: 359,
    order: 25,
  ),
  Sura(
    name: 'الشعراء',
    isMakka: true,
    verseNumbers: 227,
    pageNo: 367,
    order: 26,
  ),
  Sura(
    name: 'النمل',
    isMakka: true,
    verseNumbers: 93,
    pageNo: 377,
    order: 27,
  ),
  Sura(
    name: 'القصص',
    isMakka: true,
    verseNumbers: 88,
    pageNo: 385,
    order: 28,
  ),
  Sura(
    name: 'العنكبوت',
    isMakka: true,
    verseNumbers: 69,
    pageNo: 396,
    order: 29,
  ),
  Sura(
    name: 'الروم',
    isMakka: true,
    verseNumbers: 60,
    pageNo: 404,
    order: 30,
  ),
  Sura(
    name: 'لقمان',
    isMakka: true,
    verseNumbers: 34,
    pageNo: 411,
    order: 31,
  ),
  Sura(
    name: 'السجدة',
    isMakka: true,
    verseNumbers: 30,
    pageNo: 415,
    order: 32,
  ),
  Sura(
    name: 'الأحزاب',
    isMakka: true,
    verseNumbers: 73,
    pageNo: 418,
    order: 33,
  ),
  Sura(
    name: 'سبأ',
    isMakka: false,
    verseNumbers: 54,
    pageNo: 428,
    order: 34,
  ),
  Sura(
    name: 'فاطر',
    isMakka: true,
    verseNumbers: 45,
    pageNo: 434,
    order: 35,
  ),
  Sura(
    name: 'يس',
    isMakka: true,
    verseNumbers: 83,
    pageNo: 440,
    order: 36,
  ),
  Sura(
    name: 'الصآفّات',
    isMakka: true,
    verseNumbers: 182,
    pageNo: 446,
    order: 37,
  ),
  Sura(
    name: 'ص',
    isMakka: true,
    verseNumbers: 88,
    pageNo: 453,
    order: 38,
  ),
  Sura(
    name: 'الزُمر',
    isMakka: true,
    verseNumbers: 75,
    pageNo: 458,
    order: 39,
  ),
  Sura(
    name: 'غافر',
    isMakka: true,
    verseNumbers: 85,
    pageNo: 467,
    order: 40,
  ),
  Sura(
    name: 'فُصّلت',
    isMakka: true,
    verseNumbers: 54,
    pageNo: 477,
    order: 41,
  ),
  Sura(
    name: 'الشورى',
    isMakka: true,
    verseNumbers: 53,
    pageNo: 483,
    order: 42,
  ),
  Sura(
    name: 'الزخرف',
    isMakka: true,
    verseNumbers: 89,
    pageNo: 489,
    order: 43,
  ),
  Sura(
    name: 'الدخان',
    isMakka: true,
    verseNumbers: 59,
    pageNo: 496,
    order: 44,
  ),
  Sura(
    name: 'الجاثية',
    isMakka: true,
    verseNumbers: 37,
    pageNo: 499,
    order: 45,
  ),
  Sura(
    name: 'الأحقاف',
    isMakka: true,
    verseNumbers: 35,
    pageNo: 502,
    order: 46,
  ),
  Sura(
    name: 'محمد',
    isMakka: false,
    verseNumbers: 38,
    pageNo: 507,
    order: 47,
  ),
  Sura(
    name: 'الفتح',
    isMakka: false,
    verseNumbers: 29,
    pageNo: 511,
    order: 48,
  ),
  Sura(
    name: 'الحجرات',
    isMakka: false,
    verseNumbers: 18,
    pageNo: 515,
    order: 49,
  ),
  Sura(
    name: 'ق',
    isMakka: true,
    verseNumbers: 45,
    pageNo: 518,
    order: 50,
  ),
  Sura(
    name: 'الذاريات',
    isMakka: true,
    verseNumbers: 60,
    pageNo: 520,
    order: 51,
  ),
  Sura(
    name: 'الطور',
    isMakka: true,
    verseNumbers: 49,
    pageNo: 523,
    order: 52,
  ),
  Sura(
    name: 'النجم',
    isMakka: true,
    verseNumbers: 62,
    pageNo: 526,
    order: 53,
  ),
  Sura(
    name: 'القمر',
    isMakka: true,
    verseNumbers: 55,
    pageNo: 528,
    order: 54,
  ),
  Sura(
    name: 'الرحمن',
    isMakka: false,
    verseNumbers: 78,
    pageNo: 531,
    order: 55,
  ),
  Sura(
    name: 'الواقعة',
    isMakka: true,
    verseNumbers: 96,
    pageNo: 534,
    order: 56,
  ),
  Sura(
    name: 'الحديد',
    isMakka: false,
    verseNumbers: 29,
    pageNo: 537,
    order: 57,
  ),
  Sura(
    name: 'المجادلة',
    isMakka: false,
    verseNumbers: 22,
    pageNo: 542,
    order: 58,
  ),
  Sura(
    name: 'الحشر',
    isMakka: false,
    verseNumbers: 24,
    pageNo: 545,
    order: 59,
  ),
  Sura(
    name: 'الممتحنة',
    isMakka: false,
    verseNumbers: 13,
    pageNo: 549,
    order: 60,
  ),
  Sura(
    name: 'الصف',
    isMakka: false,
    verseNumbers: 14,
    pageNo: 551,
    order: 61,
  ),
  Sura(
    name: 'الجمعة',
    isMakka: false,
    verseNumbers: 11,
    pageNo: 553,
    order: 62,
  ),
  Sura(
    name: 'المنافقون',
    isMakka: false,
    verseNumbers: 11,
    pageNo: 554,
    order: 63,
  ),
  Sura(
    name: 'التغابن',
    isMakka: false,
    verseNumbers: 18,
    pageNo: 556,
    order: 64,
  ),
  Sura(
    name: 'الطلاق',
    isMakka: false,
    verseNumbers: 12,
    pageNo: 558,
    order: 65,
  ),
  Sura(
    name: 'التحريم',
    isMakka: false,
    verseNumbers: 12,
    pageNo: 560,
    order: 66,
  ),
  Sura(
    name: 'المُلك',
    isMakka: true,
    verseNumbers: 30,
    pageNo: 562,
    order: 67,
  ),
  Sura(
    name: 'القلم',
    isMakka: true,
    verseNumbers: 52,
    pageNo: 564,
    order: 68,
  ),
  Sura(
    name: 'الحآقّة',
    isMakka: true,
    verseNumbers: 52,
    pageNo: 566,
    order: 69,
  ),
  Sura(
    name: 'المعارج',
    isMakka: true,
    verseNumbers: 44,
    pageNo: 568,
    order: 70,
  ),
  Sura(
    name: 'نوح',
    isMakka: true,
    verseNumbers: 28,
    pageNo: 570,
    order: 71,
  ),
  Sura(
    name: 'الجنّ',
    isMakka: true,
    verseNumbers: 28,
    pageNo: 572,
    order: 72,
  ),
  Sura(
    name: 'المُزمّل',
    isMakka: true,
    verseNumbers: 20,
    pageNo: 574,
    order: 73,
  ),
  Sura(
    name: 'المُدثر',
    isMakka: true,
    verseNumbers: 56,
    pageNo: 575,
    order: 74,
  ),
  Sura(
    name: 'القيامة',
    isMakka: true,
    verseNumbers: 40,
    pageNo: 577,
    order: 75,
  ),
  Sura(
    name: 'الإنسان',
    isMakka: false,
    verseNumbers: 31,
    pageNo: 578,
    order: 76,
  ),
  Sura(
    name: 'المُرسلات',
    isMakka: true,
    verseNumbers: 50,
    pageNo: 580,
    order: 77,
  ),
  Sura(
    name: 'النبأ',
    isMakka: true,
    verseNumbers: 40,
    pageNo: 582,
    order: 78,
  ),
  Sura(
    name: 'النازعات',
    isMakka: true,
    verseNumbers: 46,
    pageNo: 583,
    order: 79,
  ),
  Sura(
    name: 'عـبـس',
    isMakka: true,
    verseNumbers: 42,
    pageNo: 585,
    order: 80,
  ),
  Sura(
    name: 'التكوير',
    isMakka: true,
    verseNumbers: 29,
    pageNo: 586,
    order: 81,
  ),
  Sura(
    name: 'الإنفطار',
    isMakka: true,
    verseNumbers: 19,
    pageNo: 587,
    order: 82,
  ),
  Sura(
    name: 'المطففين',
    isMakka: true,
    verseNumbers: 36,
    pageNo: 587,
    order: 83,
  ),
  Sura(
    name: 'الإنشقاق',
    isMakka: true,
    verseNumbers: 36,
    pageNo: 587,
    order: 84,
  ),
  Sura(
    name: 'البروج',
    isMakka: true,
    verseNumbers: 25,
    pageNo: 589,
    order: 85,
  ),
  Sura(
    name: 'الطارق',
    isMakka: true,
    verseNumbers: 22,
    pageNo: 590,
    order: 86,
  ),
  Sura(
    name: 'الأعلى',
    isMakka: true,
    verseNumbers: 17,
    pageNo: 591,
    order: 87,
  ),
  Sura(
    name: 'الفاشية',
    isMakka: true,
    verseNumbers: 19,
    pageNo: 591,
    order: 88,
  ),
  Sura(
    name: 'الفجر',
    isMakka: true,
    verseNumbers: 26,
    pageNo: 592,
    order: 89,
  ),
  Sura(
    name: 'البلد',
    isMakka: true,
    verseNumbers: 30,
    pageNo: 593,
    order: 90,
  ),
  Sura(
    name: 'الشمس',
    isMakka: true,
    verseNumbers: 20,
    pageNo: 594,
    order: 91,
  ),
  Sura(
    name: 'الليل',
    isMakka: true,
    verseNumbers: 15,
    pageNo: 595,
    order: 92,
  ),
  Sura(
    name: 'الضحى',
    isMakka: true,
    verseNumbers: 21,
    pageNo: 595,
    order: 93,
  ),
  Sura(
    name: 'الشرح',
    isMakka: true,
    verseNumbers: 11,
    pageNo: 596,
    order: 94,
  ),
  Sura(
    name: 'التين',
    isMakka: true,
    verseNumbers: 8,
    pageNo: 596,
    order: 95,
  ),
  Sura(
    name: 'العلق',
    isMakka: true,
    verseNumbers: 8,
    pageNo: 597,
    order: 96,
  ),
  Sura(
    name: 'القدر',
    isMakka: true,
    verseNumbers: 19,
    pageNo: 597,
    order: 97,
  ),
  Sura(
    name: 'البينة',
    isMakka: true,
    verseNumbers: 5,
    pageNo: 598,
    order: 98,
  ),
  Sura(
    name: 'الزلزلة',
    isMakka: false,
    verseNumbers: 8,
    pageNo: 598,
    order: 99,
  ),
  Sura(
    name: 'العاديات',
    isMakka: false,
    verseNumbers: 8,
    pageNo: 599,
    order: 100,
  ),
  Sura(
    name: 'القارعة',
    isMakka: true,
    verseNumbers: 11,
    pageNo: 599,
    order: 101,
  ),
  Sura(
    name: 'التكاثر',
    isMakka: true,
    verseNumbers: 11,
    pageNo: 600,
    order: 102,
  ),
  Sura(
    name: 'العصر',
    isMakka: true,
    verseNumbers: 8,
    pageNo: 600,
    order: 103,
  ),
  Sura(
    name: 'الهمزة',
    isMakka: true,
    verseNumbers: 3,
    pageNo: 601,
    order: 104,
  ),
  Sura(
    name: 'الفيل',
    isMakka: true,
    verseNumbers: 9,
    pageNo: 601,
    order: 105,
  ),
  Sura(
    name: 'قريش',
    isMakka: true,
    verseNumbers: 5,
    pageNo: 601,
    order: 106,
  ),
  Sura(
    name: 'الماعون',
    isMakka: true,
    verseNumbers: 4,
    pageNo: 602,
    order: 107,
  ),
  Sura(
    name: 'الكوثر',
    isMakka: true,
    verseNumbers: 7,
    pageNo: 602,
    order: 108,
  ),
  Sura(
    name: 'الكافرون',
    isMakka: true,
    verseNumbers: 3,
    pageNo: 602,
    order: 109,
  ),
  Sura(
    name: 'النصر',
    isMakka: true,
    verseNumbers: 6,
    pageNo: 603,
    order: 110,
  ),
  Sura(
    name: 'المسد',
    isMakka: false,
    verseNumbers: 3,
    pageNo: 603,
    order: 111,
  ),
  Sura(
    name: 'الإخلاص',
    isMakka: true,
    verseNumbers: 5,
    pageNo: 603,
    order: 112,
  ),
  Sura(
    name: 'الفلق',
    isMakka: true,
    verseNumbers: 4,
    pageNo: 604,
    order: 113,
  ),
  Sura(
    name: 'الناس',
    isMakka: true,
    verseNumbers: 5,
    pageNo: 604,
    order: 114,
  ),
];
